In [19]:
import pandas as pd

In [20]:
philly_weather = pd.read_csv('../../data/data/raw/philly_weather.csv')

In [21]:
philly_weather.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN
0,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/1/2020,9.17,0.00,0.0,0.0,42,29
1,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/2/2020,4.03,0.00,0.0,0.0,47,27
2,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/3/2020,4.47,0.21,0.0,0.0,49,43
3,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/4/2020,7.16,0.15,0.0,0.0,54,42
4,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/5/2020,16.33,0.00,0.0,0.0,42,35

In [22]:
philly_weather = philly_weather.rename(columns={
    "STATION": "station",
    "NAME": "location",
    "LATITUDE": "latitude",
    "LONGITUDE": "longitude",
    "ELEVATION": "elevation",
    "DATE": "date",
    "AWND": "avg_wind",
    "PRCP": "precip",
    "SNOW": "snow",
    "SNWD": "snow_ground",
    "TMAX": "max_temp",
    "TMIN": "min_temp",
})

In [23]:
philly_weather.head()

,station,location,latitude,longitude,elevation,date,avg_wind,precip,snow,snow_ground,max_temp,min_temp
0,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/1/2020,9.17,0.00,0.0,0.0,42,29
1,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/2/2020,4.03,0.00,0.0,0.0,47,27
2,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/3/2020,4.47,0.21,0.0,0.0,49,43
3,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/4/2020,7.16,0.15,0.0,0.0,54,42
4,USW00013739,"PHILADELPHIA INTERNATIONAL AIRPORT, PA US",39.87326,-75.22681,2.1,1/5/2020,16.33,0.00,0.0,0.0,42,35

In [24]:
philly_weather = philly_weather.drop(['station', 'location'], axis=1)

In [25]:
philly_weather['date'] = pd.to_datetime(philly_weather['date'])

In [26]:
philly_weather.head()

,latitude,longitude,elevation,date,avg_wind,precip,snow,snow_ground,max_temp,min_temp
0,39.87326,-75.22681,2.1,2020-01-01,9.17,0.00,0.0,0.0,42,29
1,39.87326,-75.22681,2.1,2020-01-02,4.03,0.00,0.0,0.0,47,27
2,39.87326,-75.22681,2.1,2020-01-03,4.47,0.21,0.0,0.0,49,43
3,39.87326,-75.22681,2.1,2020-01-04,7.16,0.15,0.0,0.0,54,42
4,39.87326,-75.22681,2.1,2020-01-05,16.33,0.00,0.0,0.0,42,35

In [27]:
weather = philly_weather.drop(['latitude', 'longitude', 'elevation'], axis=1)

In [28]:
weather.head()

        date  avg_wind  precip  snow  snow_ground  max_temp  min_temp
0 2020-01-01      9.17    0.00   0.0          0.0        42        29
1 2020-01-02      4.03    0.00   0.0          0.0        47        27
2 2020-01-03      4.47    0.21   0.0          0.0        49        43
3 2020-01-04      7.16    0.15   0.0          0.0        54        42
4 2020-01-05     16.33    0.00   0.0          0.0        42        35

In [29]:
weather.to_csv("weather.csv", index=False)